### ISSUE TITLE
Bug: SIGSYS: bad system call when running on pixel 4 xl

### ISSUE THREAD

**Issue by douo** [quackduck/uniclip#19]
**Description of the bug**

device: Pixel 4XL
OS: Android 13
uniclip version:  uniclip_2.3.6_Linux_arm64

```
./uniclip <ip>:44221
Connected to the clipboard
SIGSYS: bad system call
PC=0x12820 m=0 sigcode=1

goroutine 1 [syscall]:
syscall.Syscall6(0x40000e2140?, 0x38?, 0x38?, 0x40000e2180?, 0x0?, 0x4f?, 0xffffffffffffff9c?)
        /opt/homebrew/opt/go/libexec/src/syscall/syscall_linux.go:91 +0x2c fp=0x4000093900 sp=0x4000093870 pc=0x9c65c
syscall.faccessat2(0x40000e2140?, {0x40000e2140?, 0x7c8ac67328?}, 0x1, 0xc0?)
        /opt/homebrew/opt/go/libexec/src/syscall/zsyscall_linux_arm64.go:33 +0x84 fp=0x4000093970 sp=0x4000093900 pc=0x9a1a4
syscall.Faccessat(0x40000e2140?, {0x40000e2140, 0x38}, 0x1, 0x200)
        /opt/homebrew/opt/go/libexec/src/syscall/syscall_linux.go:167 +0x3c fp=0x4000093a60 sp=0x4000093970 pc=0x9899c
internal/syscall/unix.Eaccess(...)
        /opt/homebrew/opt/go/libexec/src/internal/syscall/unix/eaccess_linux.go:10
os/exec.findExecutable({0x40000e2140, 0x38})
        /opt/homebrew/opt/go/libexec/src/os/exec/lp_unix.go:31 +0x58 fp=0x4000093ab0 sp=0x4000093a60 pc=0x118e58
os/exec.LookPath({0x15c4c8, 0x14})
        /opt/homebrew/opt/go/libexec/src/os/exec/lp_unix.go:71 +0x1b8 fp=0x4000093b50 sp=0x4000093ab0 pc=0x119128
main.runGetClipCommand()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:320 +0x68 fp=0x4000093bf0 sp=0x4000093b50 pc=0x11f0d8
main.getLocalClip(...)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:338
main.MonitorLocalClip(0x18c6e0?)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:141 +0x20 fp=0x4000093c20 sp=0x4000093bf0 pc=0x11e360
main.ConnectToServer({0x7fe98734e8, 0x14})
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:135 +0x2e0 fp=0x4000093d40 sp=0x4000093c20 pc=0x11e1c0
main.main()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:83 +0x8f8 fp=0x4000093f70 sp=0x4000093d40 pc=0x11d608
runtime.main()
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:250 +0x200 fp=0x4000093fd0 sp=0x4000093f70 pc=0x44b30
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000093fd0 sp=0x4000093fd0 pc=0x71984

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000046fa0 sp=0x4000046f80 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:305 +0xb0 fp=0x4000046fd0 sp=0x4000046fa0 pc=0x44d90
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000046fd0 sp=0x4000046fd0 pc=0x71984
created by runtime.init.6
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000047760 sp=0x4000047740 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcsweep.go:278 +0x98 fp=0x40000477b0 sp=0x4000047760 pc=0x31b48
runtime.gcenable.func1()
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:178 +0x28 fp=0x40000477d0 sp=0x40000477b0 pc=0x26e88
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000477d0 sp=0x40000477d0 pc=0x71984
created by runtime.gcenable
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4000066000?, 0x18a738?, 0x1?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000047f50 sp=0x4000047f30 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x26e740)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcscavenge.go:400 +0x5c fp=0x4000047f80 sp=0x4000047f50 pc=0x2fadc
runtime.bgscavenge(0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcscavenge.go:628 +0x44 fp=0x4000047fb0 sp=0x4000047f80 pc=0x30014
runtime.gcenable.func2()
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:179 +0x28 fp=0x4000047fd0 sp=0x4000047fb0 pc=0x26e28
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000047fd0 sp=0x4000047fd0 pc=0x71984
created by runtime.gcenable
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:179 +0xac

goroutine 17 [finalizer wait]:
runtime.gopark(0x40000465a8?, 0x60000000024908?, 0xc8?, 0x87?, 0x1?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000046580 sp=0x4000046560 pc=0x44f40
runtime.runfinq()
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:193 +0x100 fp=0x40000467d0 sp=0x4000046580 pc=0x25f50
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000467d0 sp=0x40000467d0 pc=0x71984
created by runtime.createfing
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:163 +0x80

goroutine 18 [runnable]:
runtime.asyncPreempt2()
        /opt/homebrew/opt/go/libexec/src/runtime/preempt.go:307 +0x3c fp=0x40000424f0 sp=0x40000424d0 pc=0x4373c
runtime.asyncPreempt()
        /opt/homebrew/opt/go/libexec/src/runtime/preempt_arm64.s:47 +0x9c fp=0x40000426e0 sp=0x40000424f0 pc=0x7253c
main.MonitorSentClips(0x0?)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:157 +0x30 fp=0x40000427b0 sp=0x40000426f0 pc=0x11e440
main.ConnectToServer.func2()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:134 +0x28 fp=0x40000427d0 sp=0x40000427b0 pc=0x11e2c8
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000427d0 sp=0x40000427d0 pc=0x71984
created by main.ConnectToServer
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:134 +0x214

r0      0xffffffffffffff9c
r1      0x40000e21c0
r2      0x1
r3      0x200
r4      0x0
r5      0x0
r6      0x0
r7      0x1
r8      0x1b7
r9      0x2f7273752f73656c
r10     0x2f7273752f73656c
r11     0x6d7265742f6e6962
r12     0x6270696c632d7875
r13     0x7465672d6472616f
r14     0x8
r15     0x390f365
r16     0x40000923a0
r17     0x40000939f0
r18     0x0
r19     0x0
r20     0x7fe98724b0
r21     0x26ec80
r22     0x4000004000
r23     0x400009ae30
r24     0x0
r25     0x0
r26     0x4000093a70
r27     0x1
r28     0x40000021a0
r29     0x4000093808
lr      0x127dc
sp      0x4000093810
pc      0x12820
fault   0x0
```

**Comment by quackduck** [comment]
What in the world!!! I think this may actually be a go issue and not a uniclip issue. Looks like LookPath doesn’t work on pixel? On May 5, 2023, at 2:04 AM, Tiou Lims ***@***.***> wrote:﻿
Description of the bug
device: Pixel 4XL
OS: Android 13
uniclip version:  uniclip_2.3.6_Linux_arm64
./uniclip <ip>:44221
Connected to the clipboard
SIGSYS: bad system call
PC=0x12820 m=0 sigcode=1

goroutine 1 [syscall]:
syscall.Syscall6(0x40000e2140?, 0x38?, 0x38?, 0x40000e2180?, 0x0?, 0x4f?, 0xffffffffffffff9c?)
        /opt/homebrew/opt/go/libexec/src/syscall/syscall_linux.go:91 +0x2c fp=0x4000093900 sp=0x4000093870 pc=0x9c65c
syscall.faccessat2(0x40000e2140?, {0x40000e2140?, 0x7c8ac67328?}, 0x1, 0xc0?)
        /opt/homebrew/opt/go/libexec/src/syscall/zsyscall_linux_arm64.go:33 +0x84 fp=0x4000093970 sp=0x4000093900 pc=0x9a1a4
syscall.Faccessat(0x40000e2140?, {0x40000e2140, 0x38}, 0x1, 0x200)
        /opt/homebrew/opt/go/libexec/src/syscall/syscall_linux.go:167 +0x3c fp=0x4000093a60 sp=0x4000093970 pc=0x9899c
internal/syscall/unix.Eaccess(...)
        /opt/homebrew/opt/go/libexec/src/internal/syscall/unix/eaccess_linux.go:10
os/exec.findExecutable({0x40000e2140, 0x38})
        /opt/homebrew/opt/go/libexec/src/os/exec/lp_unix.go:31 +0x58 fp=0x4000093ab0 sp=0x4000093a60 pc=0x118e58
os/exec.LookPath({0x15c4c8, 0x14})
        /opt/homebrew/opt/go/libexec/src/os/exec/lp_unix.go:71 +0x1b8 fp=0x4000093b50 sp=0x4000093ab0 pc=0x119128
main.runGetClipCommand()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:320 +0x68 fp=0x4000093bf0 sp=0x4000093b50 pc=0x11f0d8
main.getLocalClip(...)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:338
main.MonitorLocalClip(0x18c6e0?)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:141 +0x20 fp=0x4000093c20 sp=0x4000093bf0 pc=0x11e360
main.ConnectToServer({0x7fe98734e8, 0x14})
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:135 +0x2e0 fp=0x4000093d40 sp=0x4000093c20 pc=0x11e1c0
main.main()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:83 +0x8f8 fp=0x4000093f70 sp=0x4000093d40 pc=0x11d608
runtime.main()
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:250 +0x200 fp=0x4000093fd0 sp=0x4000093f70 pc=0x44b30
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000093fd0 sp=0x4000093fd0 pc=0x71984

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000046fa0 sp=0x4000046f80 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:305 +0xb0 fp=0x4000046fd0 sp=0x4000046fa0 pc=0x44d90
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000046fd0 sp=0x4000046fd0 pc=0x71984
created by runtime.init.6
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000047760 sp=0x4000047740 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcsweep.go:278 +0x98 fp=0x40000477b0 sp=0x4000047760 pc=0x31b48
runtime.gcenable.func1()
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:178 +0x28 fp=0x40000477d0 sp=0x40000477b0 pc=0x26e88
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000477d0 sp=0x40000477d0 pc=0x71984
created by runtime.gcenable
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4000066000?, 0x18a738?, 0x1?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000047f50 sp=0x4000047f30 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x26e740)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcscavenge.go:400 +0x5c fp=0x4000047f80 sp=0x4000047f50 pc=0x2fadc
runtime.bgscavenge(0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcscavenge.go:628 +0x44 fp=0x4000047fb0 sp=0x4000047f80 pc=0x30014
runtime.gcenable.func2()
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:179 +0x28 fp=0x4000047fd0 sp=0x4000047fb0 pc=0x26e28
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000047fd0 sp=0x4000047fd0 pc=0x71984
created by runtime.gcenable
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:179 +0xac

goroutine 17 [finalizer wait]:
runtime.gopark(0x40000465a8?, 0x60000000024908?, 0xc8?, 0x87?, 0x1?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x4000046580 sp=0x4000046560 pc=0x44f40
runtime.runfinq()
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:193 +0x100 fp=0x40000467d0 sp=0x4000046580 pc=0x25f50
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000467d0 sp=0x40000467d0 pc=0x71984
created by runtime.createfing
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:163 +0x80

goroutine 18 [runnable]:
runtime.asyncPreempt2()
        /opt/homebrew/opt/go/libexec/src/runtime/preempt.go:307 +0x3c fp=0x40000424f0 sp=0x40000424d0 pc=0x4373c
runtime.asyncPreempt()
        /opt/homebrew/opt/go/libexec/src/runtime/preempt_arm64.s:47 +0x9c fp=0x40000426e0 sp=0x40000424f0 pc=0x7253c
main.MonitorSentClips(0x0?)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:157 +0x30 fp=0x40000427b0 sp=0x40000426f0 pc=0x11e440
main.ConnectToServer.func2()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:134 +0x28 fp=0x40000427d0 sp=0x40000427b0 pc=0x11e2c8
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000427d0 sp=0x40000427d0 pc=0x71984
created by main.ConnectToServer
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:134 +0x214

r0      0xffffffffffffff9c
r1      0x40000e21c0
r2      0x1
r3      0x200
r4      0x0
r5      0x0
r6      0x0
r7      0x1
r8      0x1b7
r9      0x2f7273752f73656c
r10     0x2f7273752f73656c
r11     0x6d7265742f6e6962
r12     0x6270696c632d7875
r13     0x7465672d6472616f
r14     0x8
r15     0x390f365
r16     0x40000923a0
r17     0x40000939f0
r18     0x0
r19     0x0
r20     0x7fe98724b0
r21     0x26ec80
r22     0x4000004000
r23     0x400009ae30
r24     0x0
r25     0x0
r26     0x4000093a70
r27     0x1
r28     0x40000021a0
r29     0x4000093808
lr      0x127dc
sp      0x4000093810
pc      0x12820
fault   0x0

**Comment by wwxiaoqi** [comment]
I encountered a similar issue, but it happened when I had a device connected. Everything works fine if I access it using root privileges.

The device is from Samsung.

```
➜  ~ uniclip --debug
Starting a new clipboard
Run `uniclip 198.18.0.1:40519` to join this clipboard

Connected to device at 192.168.0.11:47786
SIGSYS: bad system call
PC=0x12820 m=0 sigcode=1

goroutine 6 [syscall]:
syscall.Syscall6(0x400001a140?, 0x38?, 0x38?, 0x400001a180?, 0x0?, 0x4f?, 0xffffffffffffff9c?)
        /opt/homebrew/opt/go/libexec/src/syscall/syscall_linux.go:91 +0x2c fp=0x4000104b80 sp=0x4000104af0 pc=0x9c65c
syscall.faccessat2(0x400001a140?, {0x400001a140?, 0x7bb7dd9fa8?}, 0x1, 0xc0?)
        /opt/homebrew/opt/go/libexec/src/syscall/zsyscall_linux_arm64.go:33 +0x84 fp=0x4000104bf0 sp=0x4000104b80 pc=0x9a1a4
syscall.Faccessat(0x400001a140?, {0x400001a140, 0x38}, 0x1, 0x200)
        /opt/homebrew/opt/go/libexec/src/syscall/syscall_linux.go:167 +0x3c fp=0x4000104ce0 sp=0x4000104bf0 pc=0x9899c
internal/syscall/unix.Eaccess(...)
        /opt/homebrew/opt/go/libexec/src/internal/syscall/unix/eaccess_linux.go:10
os/exec.findExecutable({0x400001a140, 0x38})
        /opt/homebrew/opt/go/libexec/src/os/exec/lp_unix.go:31 +0x58 fp=0x4000104d30 sp=0x4000104ce0 pc=0x118e58
os/exec.LookPath({0x15c4c8, 0x14})
        /opt/homebrew/opt/go/libexec/src/os/exec/lp_unix.go:71 +0x1b8 fp=0x4000104dd0 sp=0x4000104d30 pc=0x119128
main.runGetClipCommand()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:320 +0x68 fp=0x4000104e70 sp=0x4000104dd0 pc=0x11f0d8
main.getLocalClip(...)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:338
main.MonitorLocalClip(0x2a2350?)
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:141 +0x20 fp=0x4000104ea0 sp=0x4000104e70 pc=0x11e360
main.HandleClient({0x18dac8?, 0x400000e4a0})
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:117 +0x33c fp=0x4000104fb0 sp=0x4000104ea0 pc=0x11ddbc
main.makeServer.func2()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:107 +0x2c fp=0x4000104fd0 sp=0x4000104fb0 pc=0x11d9dc
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000104fd0 sp=0x4000104fd0 pc=0x71984
created by main.makeServer
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:107 +0x1f0

goroutine 1 [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x400005f780 sp=0x400005f760 pc=0x44f40
runtime.netpollblock(0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/netpoll.go:527 +0x158 fp=0x400005f7c0 sp=0x400005f780 pc=0x3de68
internal/poll.runtime_pollWait(0x7b909fef28, 0x72)
        /opt/homebrew/opt/go/libexec/src/runtime/netpoll.go:306 +0xa0 fp=0x400005f7f0 sp=0x400005f7c0 pc=0x6c760
internal/poll.(*pollDesc).wait(0x4000126000?, 0x1?, 0x0)
        /opt/homebrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28 fp=0x400005f820 sp=0x400005f7f0 pc=0xb00c8
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x4000126000)
        /opt/homebrew/opt/go/libexec/src/internal/poll/fd_unix.go:614 +0x250 fp=0x400005f8d0 sp=0x400005f820 pc=0xb13c0
net.(*netFD).accept(0x4000126000)
        /opt/homebrew/opt/go/libexec/src/net/fd_unix.go:172 +0x28 fp=0x400005f990 sp=0x400005f8d0 pc=0xffe48
net.(*TCPListener).accept(0x400000c468)
        /opt/homebrew/opt/go/libexec/src/net/tcpsock_posix.go:148 +0x28 fp=0x400005f9c0 sp=0x400005f990 pc=0x10f288
net.(*TCPListener).Accept(0x400000c468)
        /opt/homebrew/opt/go/libexec/src/net/tcpsock.go:297 +0x2c fp=0x400005fa00 sp=0x400005f9c0 pc=0x10e5ac
main.makeServer()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:101 +0x200 fp=0x400005fb10 sp=0x400005fa00 pc=0x11d890
main.main()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:86 +0x908 fp=0x400005fd40 sp=0x400005fb10 pc=0x11d618
main.main()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:65 +0x498 fp=0x400005ff70 sp=0x400005fd40 pc=0x11d1a8
runtime.main()
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:250 +0x200 fp=0x400005ffd0 sp=0x400005ff70 pc=0x44b30
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400005ffd0 sp=0x400005ffd0 pc=0x71984

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x400004efa0 sp=0x400004ef80 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.forcegchelper()
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:305 +0xb0 fp=0x400004efd0 sp=0x400004efa0 pc=0x44d90
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400004efd0 sp=0x400004efd0 pc=0x71984
created by runtime.init.6
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x400004f760 sp=0x400004f740 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcsweep.go:278 +0x98 fp=0x400004f7b0 sp=0x400004f760 pc=0x31b48
runtime.gcenable.func1()
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:178 +0x28 fp=0x400004f7d0 sp=0x400004f7b0 pc=0x26e88
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400004f7d0 sp=0x400004f7d0 pc=0x71984
created by runtime.gcenable
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4000024070?, 0x18a738?, 0x1?, 0x0?, 0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x400004ff50 sp=0x400004ff30 pc=0x44f40
runtime.goparkunlock(...)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x26e740)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcscavenge.go:400 +0x5c fp=0x400004ff80 sp=0x400004ff50 pc=0x2fadc
runtime.bgscavenge(0x0?)
        /opt/homebrew/opt/go/libexec/src/runtime/mgcscavenge.go:628 +0x44 fp=0x400004ffb0 sp=0x400004ff80 pc=0x30014
runtime.gcenable.func2()
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:179 +0x28 fp=0x400004ffd0 sp=0x400004ffb0 pc=0x26e28
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400004ffd0 sp=0x400004ffd0 pc=0x71984
created by runtime.gcenable
        /opt/homebrew/opt/go/libexec/src/runtime/mgc.go:179 +0xac

goroutine 5 [finalizer wait]:
runtime.gopark(0x400004e5a8?, 0x60000000024908?, 0xc8?, 0xac?, 0x1?)
        /opt/homebrew/opt/go/libexec/src/runtime/proc.go:381 +0xe0 fp=0x400004e580 sp=0x400004e560 pc=0x44f40
runtime.runfinq()
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:193 +0x100 fp=0x400004e7d0 sp=0x400004e580 pc=0x25f50
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400004e7d0 sp=0x400004e7d0 pc=0x71984
created by runtime.createfing
        /opt/homebrew/opt/go/libexec/src/runtime/mfinal.go:163 +0x80

goroutine 7 [runnable]:
main.HandleClient.func2()
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:116 fp=0x4000050fd0 sp=0x4000050fd0 pc=0x11de10
runtime.goexit()
        /opt/homebrew/opt/go/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000050fd0 sp=0x4000050fd0 pc=0x71984
created by main.HandleClient
        /Users/ishan/code/old/GitHub/go/uniclip/uniclip.go:116 +0x334

r0      0xffffffffffffff9c
r1      0x400001a1c0
r2      0x1
r3      0x200
r4      0x0
r5      0x0
r6      0x0
r7      0x1
r8      0x1b7
r9      0x2f7273752f73656c
r10     0x2f7273752f73656c
r11     0x6d7265742f6e6962
r12     0x6270696c632d7875
r13     0x7465672d6472616f
r14     0x8
r15     0x0
r16     0x40001043a0
r17     0x4000104c70
r18     0x0
r19     0x0
r20     0x0
r21     0x11d9dc
r22     0x71984
r23     0x4000104e30
r24     0x0
r25     0x0
r26     0x4000104cf0
r27     0x0
r28     0x4000003a00
r29     0x4000104a88
lr      0x127dc
sp      0x4000104a90
pc      0x12820
fault   0x0
➜  ~⏎  
```

**Comment by vector090** [comment]
Got the same problem in MIUI.
Solved by compiling by myself:

GOOS=android GOARCH=arm64 go build 

The generated uniclip is 4 MB+ instead of 2.5 MB as in releases/download/v2.3.6/uniclip_2.3.6_Linux_arm64.tar.gz, and my build works fine.

Download and and try:
https://github.com/user-attachments/files/21044839/uniclip_2.3.6_Linux_arm64.tar.gz

My go version is
go version go1.22.2 linux/amd64
